version: '3.8'

services:
  file-service:
    build: ./
    ports:
      - '3033:3000'
    volumes:
      - ./uploads/public:/app/uploads/public

  minio:
    image: docker.io/bitnami/minio:2022
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: supersecret
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'

volumes:
  minio_data:
    driver: local